### ISSUE TITLE
MP4: file fails to load

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dhamaniasad/mutagen#133]
```
http://code.google.com/p/quodlibet/issues/detail?id=1098
http://www.mediafire.com/?4f3q51dxhbn331o

W: Error loading '/home/mint/Desktop/Uka - Tenger hogjim toglosoor.m4a'
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/quodlibet/formats/__init__.py", line 61, 
in MusicFile
return _infos[ext](filename)
File "/usr/lib/python2.7/dist-packages/quodlibet/formats/mp4.py", line 65, in 
__init__
audio = MP4(filename)
File "/usr/lib/python2.7/dist-packages/mutagen/__init__.py", line 73, in 
__init__
self.load(filename, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/mutagen/mp4.py", line 660, in load
try: self.info = MP4Info(atoms, fileobj)
File "/usr/lib/python2.7/dist-packages/mutagen/mp4.py", line 587, in __init__
for trak in list(atoms["moov"].findall("trak")):
File "/usr/lib/python2.7/dist-packages/mutagen/mp4.py", line 177, in __getitem__
raise KeyError, "%s not found" % names[0]
MP4StreamInfoError: 'moov not found'
```

Original issue reported on code.google.com by `reiter.christoph@gmail.com` on 4 Jan 2013 at 3:46
- Merged into: #15

**Comment by GoogleCodeExporter** [comment]
```
It's an AAC file, no MP4.
```

Original comment by `reiter.christoph@gmail.com` on 3 Apr 2013 at 4:18
- Changed state: **Duplicate**
