### ISSUE TITLE
OggFlac fails to load

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dhamaniasad/mutagen#140]
```
File: http://www.sendspace.com/file/fttv9k
QL bug: https://code.google.com/p/quodlibet/issues/detail?id=1139

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/mutagen/__init__.py", line 215, in File
    if score > 0: return Kind(filename)
  File "/usr/lib/python2.7/dist-packages/mutagen/__init__.py", line 73, in __init__
    self.load(filename, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mutagen/ogg.py", line 444, in load
    self.info = self._Info(fileobj)
  File "/usr/lib/python2.7/dist-packages/mutagen/flac.py", line 86, in __init__
    self.load(data)
  File "/usr/lib/python2.7/dist-packages/mutagen/oggflac.py", line 49, in load
    page = OggPage(data)
  File "/usr/lib/python2.7/dist-packages/mutagen/ogg.py", line 74, in __init__
    header = fileobj.read(27)
  File "/usr/lib/python2.7/dist-packages/mutagen/flac.py", line 57, in read
    size, len(data)))
mutagen.flac.error: file said 27 bytes, read 0 bytes

```

Original issue reported on code.google.com by `reiter.christoph@gmail.com` on 6 Apr 2013 at 10:54

**Comment by GoogleCodeExporter** [comment]
```
It's not an OggFLAC, it a standard FLAC in an Ogg stream.

Since these can't be tagged (at least in no sane way).. closing.
```

Original comment by `reiter.christoph@gmail.com` on 17 May 2013 at 6:00
- Changed state: **WontFix**
