### ISSUE TITLE
Mutagen EasyID3 function throws LookupError when compiled

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dhamaniasad/mutagen#22]
```
I compiled my python program with PY2EXE. If i simply run the program i 
get no error, only in the compiled version. 
(I'm using latest PY2EXE and latest python 2.6)

This is the line in my code that throws the error:
EasyID3("someFile.mp3")    # this is line 131 in my code
the exception log:
Traceback (most recent call last):
  File "main.py", line 96, in OnSearch
  File "main.py", line 131, in searchMP3s
  File "mutagen\easyid3.pyo", line 63, in __init__
  File "mutagen\id3.pyo", line 136, in load
  File "mutagen\id3.pyo", line 282, in __read_frames
  File "mutagen\id3.pyo", line 305, in __load_framedata
  File "mutagen\id3.pyo", line 1047, in fromData
  File "mutagen\id3.pyo", line 980, in _readData
  File "mutagen\id3.pyo", line 702, in read
  File "mutagen\id3.pyo", line 683, in read
LookupError: unknown encoding: latin1
```

Original issue reported on code.google.com by `forian...@gmail.com` on 4 Sep 2009 at 8:10

**Comment by GoogleCodeExporter** [comment]
```
py2exe has known issues with detecting use of encodings. You may need to 
manually
include the codecs module (and not pass -a to your build script).
```

Original comment by `joe.wreschnig@gmail.com` on 7 Sep 2009 at 6:05
- Changed state: **Invalid**
