### ISSUE TITLE
mutagen.easyid3: Circular dependency on mutagen.id3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dhamaniasad/mutagen#32]
```
Importing mutagen.easyid3 fails when mutagen.id3 or mutagen.mp3 have not
been imported prior to.

Mutagen 1.16 does not have this problem.

>>> import mutagen.easyid3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/mutagen/easyid3.py", line 18, in
<module>
    import mutagen.id3
  File "/usr/lib/python2.6/site-packages/mutagen/id3.py", line 1989, in
<module>
    class EasyID3FileType(ID3FileType):
  File "/usr/lib/python2.6/site-packages/mutagen/id3.py", line 1990, in
EasyID3FileType
    from mutagen.easyid3 import EasyID3 as ID3
ImportError: cannot import name EasyID3
>>>

```

Original issue reported on code.google.com by `nondicti...@gmail.com` on 23 Oct 2009 at 12:50

**Comment by GoogleCodeExporter** [comment]
Original comment by `joe.wreschnig@gmail.com` on 23 Oct 2009 at 3:23
- Changed title: **mutagen.easyid3: Circular dependency on mutagen.id3**
- Added labels: **Type-Defect**, **Priority-High**
- Removed labels: **Type-Enhancement**, **Priority-Low**

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r60.
```

Original comment by `joe.wreschnig@gmail.com` on 23 Oct 2009 at 5:33
- Changed state: **Fixed**
