### ISSUE TITLE
[regression] mutagen 1.19 fails to open certain FLAC files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dhamaniasad/mutagen#67]
```
Hi,

I recently updated mutagen from version 1.18 to 1.19 and noticed a regression 
with FLAC files.

File example is hosted here:
http://www.math.uni-bielefeld.de/~tjakobi/archive/regression.flac

The output I'm getting:
Python 2.6.5 (release26-maint, Jun 23 2010, 11:36:49) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mutagen.flac
>>> audio = mutagen.flac.FLAC('APPLESEED ORIGINAL SOUNDTRACK (Disc 
1)-track01.flac')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/mutagen/__init__.py", line 75, in __init__
    self.load(filename, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mutagen/flac.py", line 587, in load
    raise FLACNoHeaderError("End of metadata did not start audio")
mutagen.flac.FLACNoHeaderError: End of metadata did not start audio

The file was created with flake SVN-r264 (the FLAC encoder where parts are now 
in ffmpeg), and the tagging was done with foobar2000 0.9.6.8 (through wine).

metaflac can read the tags perfectly and the flac reference decoder shows no 
warnings/errors.

mutagen 1.18 did handle the files correctly.

Greets,
Tobias

```

Original issue reported on code.google.com by `cubi...@googlemail.com` on 24 Jun 2010 at 1:01

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r87.
```

Original comment by `joe.wreschnig@gmail.com` on 24 Jun 2010 at 6:16
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Woah, that was fast - big thanks!
```

Original comment by `cubi...@googlemail.com` on 24 Jun 2010 at 9:55

**Comment by GoogleCodeExporter** [comment]
```
Issue 121 has been merged into this issue.
```

Original comment by `reiter.christoph@gmail.com` on 29 Aug 2012 at 12:11

**Comment by GoogleCodeExporter** [comment]
```
Thanks! Sorry for not noticing issue #67 before re-reporting the issue.
```

Original comment by `julf.helsingius` on 29 Aug 2012 at 12:22

**Comment by GoogleCodeExporter** [comment]
```
I still seem to have the issue even with 1.20
```

Original comment by `julf.helsingius` on 29 Aug 2012 at 12:34
